networks:
  docker-network:  

volumes:
  mysql-volume: {}

services:
  mysql_eight:
    image: mysql:8
    container_name: mysql_eight
    ports:
      - "3308:3308"
    volumes:
      - mysql-volume:/var/lib/mysql/eight
      - ./init.sql:/docker-entrypoint-initdb.d/init_eight.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test
    networks:
      - docker-network

  mysql_five: # version five 
    image: mysql:5.5
    container_name: mysql_five
    ports:
      - "3305:3305" 
    volumes:
      - mysql-volume:/var/lib/mysql/five
      - ./init.sql:/docker-entrypoint-initdb.d/init_five.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test
    networks:
      - docker-network

  mysql_seven: 
    image: mysql:5.7 
    container_name: mysql_seven
    ports:
      - "3307:3307" 
    volumes:
      - mysql-volume:/var/lib/mysql/seven
      - ./init.sql:/docker-entrypoint-initdb.d/init_seven.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DB: test
    networks:
      - docker-network
